#########################################################
# Horizontal Pod AutoScaler for API service (K8s >= v1.17)
#########################################################
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api
  namespace: __DEPLOYMENT_NAMESPACE__
  labels:
    name: hpa-api
    environment: __DEPLOYMENT_NAMESPACE__
    app: __APP_NAME__
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: __MIN_REPLICA_API__
  maxReplicas: __MAX_REPLICA_API__
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---

